on: push

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up prerequisites
      run: |
        sudo apt-get install clang-6.0 libc++abi-dev libc++-dev
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-6.0 100
        sudo update-alternatives --install /usr/bin/llvm-symbolizer llvm-symbolizer /usr/bin/llvm-symbolizer-6.0 100
    - name: Run tests
      run: |
        make test
        ./test
